config/routes.rb
Rails.application.routes.draw do
  root to: 'regions#index'
  resources :regions do
    resources :animals
  end

  resources :animals do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  has_many :regions, through: :sightings
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :sightings
  has_many :animals, through: :sightings
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  belongs_to :region
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def new
    @region = Region.find(params[:region_id])
    @animal = @region.animals.new
  end

  def create
    @region = Region.find(params[:region_id])
    @animal = @region.animals.new(animal_params)
    if @animal.save
      redirect_to region_path(@animal.region)
    else
      render :new
    end
  end

  def edit
    @region = Region.find(params[:region_id])
    @animal = Animal.find(params[:id])
  end

  def update
    @region = Region.find(params[:region_id])
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to region_path(@region)
    else
      render :edit
    end
  end

  def destroy
    @region = Region.find(params[:region_id])
    animal = Animal.find(params[:id])
    animal.destroy
    redirect_to region_path(@region)
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

private
  def animal_params
    params.require(:animal).permit(:species)
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
    render :index
  end

  def show
    @region = Region.find(params[:id])
    render :show
  end

  def new
    @region = Region.new
    render :new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to regions_path
    else
      render :new
    end
  end

  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      redirect_to region_path(@region)
    else
      render :edit
    end
  end

  def edit
    @region = Region.find(params[:id])
    render :edit
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_to regions_path
  end

private
  def region_params
    params.require(:region).permit(:region_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regions/_form.html.erb
<%= form_for @region do |f| %>
  <%= f.label :region_name %>
  <%= f.text_field :region_name %>
  <%= f.submit %>
<% end %>

app/views/regions/edit.html.erb
<h3>Edit Region:</h3>


<%= render 'form' %>

app/views/regions/index.html.erb
<h1>Regions:</h1>

<ul>
  <% @regions.each do |region| %>
  <li><%= link_to region.region_name, region_path(region) %> <%= link_to 'Edit', edit_region_path(region) %> <%= link_to 'Delete', region_path(region), data: {confirm: "Gaia Protect Us (delete)?", method: "delete"}%></li>
  <% end %>
</ul>


<%= link_to "New Region", new_region_path %>

app/views/regions/new.html.erb
<h3>Create a New Region:</h3>

<%= render 'form' %>

app/views/regions/show.html.erb
<h1>Home Page for <%= @region.region_name %></h1>

<% if @region.animals.any? %>
  <h4>Animals Sighted Here:</h4>
  <ul>
    <% @region.animals.each do |animal| %>
      <li><%= link_to animal.species %></li>
    <% end %>
  </ul>
  <% else %>
    <p>No animals sighted in <%= @region.region_name %></p>
  <% end %>


<p><%= link_to 'Add a Animal', new_region_animal_path(@region)</p>